export enum AuditAction {
  // Command Center & User Management
  CREATE_CC = 'CREATE_CC',
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  CHANGE_ROLE = 'CHANGE_ROLE',

  // Authentication & Identity
  AUTH_LOGIN = 'AUTH_LOGIN',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  AUTH_REVOKE_SESSION = 'AUTH_REVOKE_SESSION',
  ACTIVATE_ACCOUNT = 'ACTIVATE_ACCOUNT',
  LINK_IDENTITY = 'LINK_IDENTITY',
  UNLINK_IDENTITY = 'UNLINK_IDENTITY',
  VERIFY_PHONE = 'VERIFY_PHONE',
  VERIFY_EMAIL = 'VERIFY_EMAIL',

  // Hardware & Pairing
  PAIR_DEVICE = 'PAIR_DEVICE',
  UNPAIR_DEVICE = 'UNPAIR_DEVICE',

  // Driver Profile & Duty Shift Management
  CHANGE_DUTY_STATUS = 'CHANGE_DUTY_STATUS',
  AUTO_EXPIRE_SHIFT = 'AUTO_EXPIRE_SHIFT',
  UPDATE_DRIVER_PROFILE = 'UPDATE_DRIVER_PROFILE',

  // Incident Lifecycle & Dispatch
  CREATE_INCIDENT = 'CREATE_INCIDENT',
  CLAIM_INCIDENT = 'CLAIM_INCIDENT',
  RELEASE_INCIDENT_CLAIM = 'RELEASE_INCIDENT_CLAIM',
  ASSIGN_RESPONDER = 'ASSIGN_RESPONDER',
  CHANGE_THREAT_LEVEL = 'CHANGE_THREAT_LEVEL',
  ESCALATE_INCIDENT = 'ESCALATE_INCIDENT',
  VERIFY_INCIDENT = 'VERIFY_INCIDENT',
  RESOLVE_INCIDENT = 'RESOLVE_INCIDENT',
  CANCEL_INCIDENT = 'CANCEL_INCIDENT',

  // Post-Incident Reporting
  SUBMIT_INCIDENT_REPORT = 'SUBMIT_INCIDENT_REPORT',
  REVIEW_INCIDENT_REPORT = 'REVIEW_INCIDENT_REPORT',
}
